// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/back-top.vue')['default']
    Banner: typeof import('./src/components/banner.vue')['default']
    Comment: typeof import('./src/components/comment.vue')['default']
    Feature: typeof import('./src/components/feature.vue')['default']
    HeaderSearch: typeof import('./src/components/header-search.vue')['default']
    LayoutBody: typeof import('./src/components/layout/layout-body.vue')['default']
    LayoutFooter: typeof import('./src/components/layout/layout-footer.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/layout-header.vue')['default']
    MenuTree: typeof import('./src/components/menu-tree.vue')['default']
    Post: typeof import('./src/components/post.vue')['default']
    Quote: typeof import('./src/components/quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/section-title.vue')['default']
    SmallIco: typeof import('./src/components/small-ico.vue')['default']
  }
}
